name: Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build

      - name: Package as ZIP
        run: npm run package

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v3
        with:
          name: GeauxBubble2React-${{ matrix.os }}
          path: dist/GeauxBubble2React.zip

      - name: Release ZIP
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push'
        with:
          files: dist/GeauxBubble2React.zip
          tag_name: v1.0.${{ github.run_number }}
          release_name: "GeauxBubble2React v1.0.${{ github.run_number }}"
          body: "Automatic release of GeauxBubble2React."
